# Generated by Django 5.0.5 on 2024-09-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0027_rename_user_role_userdetails_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveCredit",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="User Leave Credits"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave Credits",
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Leave Date"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PA", "Paid Leave"),
                            ("UN", "Unpaid Leave"),
                            ("WR", "Work-Related Trip"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                        verbose_name="Leave Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leaves",
            },
        ),
        migrations.CreateModel(
            name="LeaveApprover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="leave_approvers",
                        to="core.department",
                    ),
                ),
                (
                    "department_approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="department_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hr_approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hr_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave Approvers",
            },
        ),
    ]
