# Generated by Django 5.0.5 on 2024-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="Leave Info"),
        ),
    ]
