# Generated by Django 5.0.5 on 2024-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leave_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="approved_by_head",
            field=models.BooleanField(
                default=False, verbose_name="Approved By Dept. Head"
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by_hr",
            field=models.BooleanField(default=False, verbose_name="Approved By HR"),
        ),
    ]
