# Generated by Django 5.0.5 on 2024-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0004_leaveapprover_director_approver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="approved_by_head",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="approved_by_hr",
        ),
        migrations.AddField(
            model_name="leave",
            name="approve_status",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Leave Approve Status"
            ),
        ),
    ]
