# Generated by Django 5.0.5 on 2024-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0005_remove_leave_approved_by_head_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="approve_status",
        ),
        migrations.AddField(
            model_name="leave",
            name="approve_data",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Leave Approve Data"
            ),
        ),
    ]
