# Generated by Django 5.0.5 on 2024-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0006_remove_leave_approve_status_leave_approve_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="approve_data",
        ),
        migrations.AddField(
            model_name="leave",
            name="first_approver_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="First Leave Approver Data",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="second_approver_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Second Leave Approver Data",
            ),
        ),
    ]
