# Generated by Django 5.0.5 on 2024-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0007_remove_leave_approve_data_leave_first_approver_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavecredit",
            name="used_credits",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="User Leave Credits"
            ),
        ),
    ]
