[phases.setup]
nixPkgs = ["...", "libreoffice"]

[phases.build]
cmds = [
  "...",
  "echo "Looking for soffice..." && \
  find / -name soffice 2>/dev/null && \
  echo "Soffice search complete." && \"
]