# Generated by Django 5.0.5 on 2024-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdetails",
            options={"verbose_name_plural": "User Details"},
        ),
        migrations.AddField(
            model_name="userdetails",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="phone_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
