# Generated by Django 5.0.5 on 2024-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userdetails_options_userdetails_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="date_of_hiring",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="education",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="employee_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="rank",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
