# Generated by Django 5.0.5 on 2024-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_department_userdetails_created_userdetails_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
