# Generated by Django 5.0.5 on 2024-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_department_created_alter_department_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
