# Generated by Django 5.0.5 on 2024-05-19 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userdetails_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="created",
        ),
        migrations.AddField(
            model_name="userdetails",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
            ),
        ),
    ]
