# Generated by Django 5.0.5 on 2024-05-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_userdetails_created_userdetails_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="education",
            field=models.CharField(
                choices=[
                    ("KG", "Kindergarten"),
                    ("EL", "Elementary"),
                    ("HS", "High School"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default="BA",
                max_length=2,
            ),
        ),
    ]
