# Generated by Django 5.0.5 on 2024-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_userdetails_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="User Profile Picture"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Department Name"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="User Address"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="User Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="date_of_hiring",
            field=models.DateField(
                blank=True, null=True, verbose_name="User Date of Hiring"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="education",
            field=models.CharField(
                choices=[
                    ("KG", "Kindergarten"),
                    ("EL", "Elementary"),
                    ("HS", "High School"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default="BA",
                max_length=2,
                verbose_name="User Educational Attainment",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="employee_number",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="User Employee Number",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="User Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="rank",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="User Rank"
            ),
        ),
    ]
