# Generated by Django 5.0.5 on 2024-06-22 02:03

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_userdetails_profile_picture_alter_department_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.utils.get_user_profile_picture_directory_path,
                verbose_name="User Profile Picture",
            ),
        ),
    ]
