# Generated by Django 5.0.5 on 2024-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_userdetails_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "Departments"},
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Department Code"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
