# Generated by Django 5.0.5 on 2024-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_userdetails_department_alter_userdetails_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Is Department Active"
            ),
        ),
    ]
