# Generated by Django 5.0.5 on 2024-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_department_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KG", "Kindergarten"),
                    ("EL", "Elementary"),
                    ("HS", "High School"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Civil Status",
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KG", "Kindergarten"),
                    ("EL", "Elementary"),
                    ("HS", "High School"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Educational Attainment",
            ),
        ),
    ]
