# Generated by Django 5.0.5 on 2024-07-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userdetails_civil_status_alter_userdetails_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SI", "Single"),
                    ("MA", "Married"),
                    ("DI", "Divorced"),
                    ("WI", "Widowed"),
                    ("SE", "Separated"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Civil Status",
            ),
        ),
    ]
