# Generated by Django 5.0.5 on 2024-07-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_biometricdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biometricdetail",
            old_name="device_uid",
            new_name="uid_in_device",
        ),
    ]
