# Generated by Django 5.0.5 on 2024-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_device_uid_biometricdetail_uid_in_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human Resource"),
                    ("DH", "Department Head"),
                    ("EE", "Employee"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Role",
            ),
        ),
    ]
