# Generated by Django 5.0.5 on 2024-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_userdetails_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RC", "Roman Catholic"),
                    ("IS", "Islam"),
                    ("EV", "Evangelical"),
                    ("INC", "Iglesia ni Cristo"),
                    ("AG", "Aglipayan"),
                    ("JW", "Jehovah's Witnesses"),
                    ("BAC", "Born Again Christian"),
                    ("SDA", "Seventh-day Adventist"),
                    ("UPC", "United Pentecostal Church"),
                    ("BAP", "Baptist"),
                    ("MET", "Methodist"),
                    ("COC", "Church of Christ"),
                ],
                default=None,
                max_length=3,
                null=True,
                verbose_name="User Religious Affiliation",
            ),
        ),
    ]
