# Generated by Django 5.0.5 on 2024-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userdetails_religion"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="degrees_earned",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="User Degrees Earned",
            ),
        ),
    ]
