# Generated by Django 5.0.5 on 2024-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_userdetails_degrees_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="User Middle Name"
            ),
        ),
    ]
