# Generated by Django 5.0.5 on 2024-07-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_userdetails_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HS", "High School"),
                    ("VC", "Vocational"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Educational Attainment",
            ),
        ),
    ]
