# Generated by Django 5.0.5 on 2024-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_userdetails_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biometricdetail",
            old_name="uid_in_device",
            new_name="user_id_in_device",
        ),
    ]
