# Generated by Django 5.0.5 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_rename_uid_in_device_biometricdetail_user_id_in_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOD", "Board of Director"),
                    ("HR", "Human Resource"),
                    ("MGR", "Manager"),
                    ("DH", "Department Head"),
                    ("EMP", "Employee"),
                ],
                default=None,
                max_length=3,
                null=True,
                verbose_name="User Role",
            ),
        ),
    ]
