# Generated by Django 5.0.5 on 2024-09-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_userdetails_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdetails",
            old_name="user_role",
            new_name="role",
        ),
    ]
