# Generated by Django 5.0.5 on 2024-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_user_role_userdetails_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOD", "Board of Director"),
                    ("HR", "Human Resource"),
                    ("PRES", "President"),
                    ("DIR", "Director"),
                    ("DH", "Department Head"),
                    ("EMP", "Employee"),
                ],
                default=None,
                max_length=4,
                null=True,
                verbose_name="User Role",
            ),
        ),
    ]
