# Generated by Django 5.0.5 on 2024-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(
                default=False, verbose_name="Is Notification Read"
            ),
        ),
    ]
