# Generated by Django 5.0.5 on 2024-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_notification_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
