# Generated by Django 5.0.5 on 2024-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_notification_created_notification_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
