# Generated by Django 5.0.5 on 2024-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_notification_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Femane")],
                default=None,
                max_length=3,
                null=True,
                verbose_name="User Gender",
            ),
        ),
    ]
