# Generated by Django 5.0.5 on 2024-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_userdetails_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("ERR", "Error"), ("Act", "Activity")],
                        default=None,
                        max_length=3,
                        null=True,
                        verbose_name="User Educational Attainment",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        choices=[("ERR", "Error"), ("Act", "Activity")],
                        default=None,
                        max_length=3,
                        null=True,
                        verbose_name="User Educational Attainment",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notification Content"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "App Logs",
            },
        ),
    ]
