# Generated by Django 5.0.5 on 2024-10-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_applog_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppLog",
        ),
    ]
