# Generated by Django 5.0.5 on 2024-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_delete_applog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                default=None,
                max_length=3,
                null=True,
                verbose_name="User Gender",
            ),
        ),
    ]
