# Generated by Django 5.0.5 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_userdetails_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HR", "Human Resource"),
                    ("PRES", "President"),
                    ("DIR", "Director"),
                    ("DH", "Department Head"),
                    ("EMP", "Employee"),
                ],
                default=None,
                max_length=4,
                null=True,
                verbose_name="User Role",
            ),
        ),
    ]
