# Generated by Django 5.0.5 on 2024-11-14 13:00

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_userdetails_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_personal_files_directory_path,
                        verbose_name="Personal File",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "Diploma"),
                            ("TOR", "Transcript of Records"),
                            ("E", "Eligibility"),
                            ("C", "Certificates"),
                            ("ST", "Seminars & Trainings"),
                            ("MR", "Medical Records"),
                            ("O", "Others"),
                        ],
                        default=None,
                        max_length=3,
                        null=True,
                        verbose_name="Personal File Category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personal Files",
            },
        ),
    ]
