# Generated by Django 5.0.5 on 2024-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_personalfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalfile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="personalfile",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
