# Generated by Django 5.0.5 on 2024-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_personalfile_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalfile",
            name="academic_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HS", "High School"),
                    ("VC", "Vocational"),
                    ("BA", "Bachelor"),
                    ("MA", "Master"),
                    ("DR", "Doctorate"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Personal File Academic Degree",
            ),
        ),
        migrations.AddField(
            model_name="personalfile",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Personal File Year"
            ),
        ),
    ]
