# Generated by Django 5.0.5 on 2024-11-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_personalfile_academic_degree_personalfile_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalfile",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Personal File Name"
            ),
        ),
    ]
