# Generated by Django 5.0.5 on 2024-11-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_personalfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="workweek",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Department Workweek"
            ),
        ),
    ]
