# Generated by Django 5.0.5 on 2024-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0027_remove_shift_departments_remove_shift_multi_day_and_more"),
        ("core", "0046_department_workweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="shifts",
            field=models.ManyToManyField(
                blank=True, related_name="shifts", to="attendance.shift"
            ),
        ),
    ]
