# Generated by Django 5.0.5 on 2024-11-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_department_shifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="core.department",
            ),
        ),
    ]
