# Generated by Django 5.1.7 on 2025-04-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_applog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="can_modify_shift",
            field=models.BooleanField(
                default=False, verbose_name="User Can Modify Shifts"
            ),
        ),
    ]
