# Generated by Django 5.1.7 on 2025-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_userdetails_can_modify_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="resignation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Resignation Date"
            ),
        ),
    ]
