# Generated by Django 5.0.5 on 2024-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
