from django.urls import include, path

app_name = "performance"

from performance import views as performance_views

urlpatterns = [
    path(
        "shared-resources-management/update-file-list-after-modifying-share-access",
        performance_views.shared_resource_management_update_file_list_after_modifying_share_access,
        name="shared_resource_management_update_file_list_after_modifying_share_access",
    ),
    path(
        "shared-resources-management/<str:resource_id>/modify-users-with-share-access",
        performance_views.shared_resource_management_modify_users_with_share_access,
        name="shared_resource_management_modify_users_with_share_access",
    ),
    path(
        "shared-resources-management/<str:resource_id>/confidential-state-toggle",
        performance_views.shared_resource_management_confidential_state_toggle,
        name="shared_resource_management_confidential_state_toggle",
    ),
    path(
        "shared-resources-management/close-share-access-modal",
        performance_views.close_shared_resource_management_share_access_modal,
        name="close_shared_resource_management_share_access_modal",
    ),
    path(
        "shared-resources-management/<str:resource_id>/share-access",
        performance_views.shared_resource_management_share_access,
        name="shared_resource_management_share_access",
    ),
    path(
        "shared-resources-management/close-preview-file-modal",
        performance_views.close_shared_resource_management_preview_file_modal,
        name="close_shared_resource_management_preview_file_modal",
    ),
    path(
        "shared-resources-management/close-delete-confirmation",
        performance_views.close_shared_resource_management_delete_confirmation_modal,
        name="close_shared_resource_management_delete_confirmation_modal",
    ),
    path(
        "shared-resources-management/<str:resource_id>/view",
        performance_views.shared_resources_management_preview_resource,
        name="shared_resources_management_preview_resource",
    ),
    path(
        "shared-resources-management/<str:resource_id>/delete",
        performance_views.shared_resource_management_delete,
        name="shared_resource_management_delete",
    ),
    path(
        "shared-resources-management/upload",
        performance_views.shared_resources_management_upload,
        name="shared_resources_management_upload",
    ),
    path(
        "shared-resources-management/<str:user_id>",
        performance_views.shared_resources_management,
        name="shared_resources_management_with_user",
    ),
    path(
        "shared-resources-management",
        performance_views.shared_resources_management,
        name="shared_resources_management",
    ),
    path(
        "shared-resources/update-file-list-after-modifying-share-access",
        performance_views.resource_update_file_list_after_modifying_share_access,
        name="resource_update_file_list_after_modifying_share_access",
    ),
    path(
        "shared-resources/<str:resource_id>/modify-users-with-share-access",
        performance_views.resource_modify_users_with_share_access,
        name="resource_modify_users_with_share_access",
    ),
    path(
        "shared-resources/<str:resource_id>/share-access",
        performance_views.resource_share_access,
        name="resource_share_access",
    ),
    path(
        "shared-resources/close-preview-file-modal",
        performance_views.close_preview_file_modal,
        name="close_preview_file_modal",
    ),
    path(
        "shared-resources/<str:resource_id>/view",
        performance_views.preview_resource,
        name="preview_resource",
    ),
    path(
        "shared-resources/close-delete-confirmation",
        performance_views.close_delete_confirmation_modal,
        name="close_delete_confirmation_modal",
    ),
    path(
        "shared-resources/<str:resource_id>/delete",
        performance_views.delete_resource,
        name="delete_resource",
    ),
    path(
        "shared-resources/<str:resource_id>/download",
        performance_views.download_resource,
        name="download_resource",
    ),
    path(
        "shared-resources/upload",
        performance_views.upload_resources,
        name="upload_resources",
    ),
    path(
        "shared-resources/<str:user_id>",
        performance_views.shared_resources,
        name="shared_resources_with_user",
    ),
    path(
        "shared-resources",
        performance_views.shared_resources,
        name="shared_resources",
    ),
    path(
        "post-management/<str:post_id>/delete",
        performance_views.delete_selected_post,
        name="delete_selected_post",
    ),
    path(
        "poll-management/<str:poll_id>/delete",
        performance_views.delete_selected_poll,
        name="delete_selected_poll",
    ),
    path(
        "poll-management/<str:poll_id>/add-choice",
        performance_views.modify_poll_choices,
        name="modify_poll_choices",
    ),
    path(
        "poll-management/<str:poll_id>/toggle-status",
        performance_views.toggle_poll_status,
        name="toggle_poll_status",
    ),
    path(
        "poll-management/<str:poll_id>/stats",
        performance_views.poll_statistics,
        name="poll_statistics",
    ),
    path(
        "poll-management/<str:poll_id>",
        performance_views.poll_management,
        name="poll_management_with_selected_poll",
    ),
    path(
        "poll-management",
        performance_views.poll_management,
        name="poll_management",
    ),
    path(
        "post-management/<str:post_id>",
        performance_views.post_management,
        name="post_management_with_selected_poll",
    ),
    path(
        "post-management",
        performance_views.post_management,
        name="post_management",
    ),
    path(
        "poll-and-post/poll/<str:poll_id>/view-result",
        performance_views.view_poll_result,
        name="view_poll_result",
    ),
    path(
        "poll-and-post/poll/<str:poll_id>/submit-vote",
        performance_views.submit_poll_vote,
        name="submit_poll_vote",
    ),
    path(
        "poll-and-post/close-content-modal",
        performance_views.close_content_modal,
        name="close_content_modal",
    ),
    path(
        "poll-and-post/post/<str:content_id>",
        performance_views.select_post_content,
        name="select_post_content",
    ),
    path(
        "poll-and-post/poll/<str:content_id>",
        performance_views.select_poll_content,
        name="select_poll_content",
    ),
    path(
        "poll-and-post",
        performance_views.poll_and_post_section,
        name="poll_and_post_section",
    ),
    path(
        "user-evaluation-management/<str:user_evaluation_id>/modify-evaluator",
        performance_views.modify_user_evaluation_evaluators,
        name="modify_user_evaluation_evaluators",
    ),
    path(
        "user-evaluation-management/<str:user_evaluation_id>/finalize/toggle",
        performance_views.finalize_user_evaluation_toggle,
        name="finalize_user_evaluation_toggle",
    ),
    path(
        "user-evaluation-management/modify/reset",
        performance_views.reset_evaluation,
        name="reset_evaluation",
    ),
    path(
        "user-evaluation-management/modify/<str:pk>/<str:quarter>/<str:year>",
        performance_views.modify_user_evaluation,
        name="modify_user_evaluation",
    ),
    path(
        "user-evaluation-management/<str:year>",
        performance_views.user_evaluation_management,
        name="user_evaluation_management_filtered",
    ),
    path(
        "user-evaluation-management",
        performance_views.user_evaluation_management,
        name="user_evaluation_management",
    ),
    path(
        "evaluation/submit-user-evaluation/peer",
        performance_views.submit_peer_evaluation,
        name="submit_peer_evaluation",
    ),
    path(
        "evaluation/submit-user-evaluation",
        performance_views.submit_self_evaluation,
        name="submit_self_evaluation",
    ),
    path(
        "evaluation/submit-evaluation-rating/<str:for_peer>",
        performance_views.submit_evaluation_rating,
        name="submit_peer_evaluation_rating",
    ),
    path(
        "evaluation/submit-evaluation-rating",
        performance_views.submit_evaluation_rating,
        name="submit_evaluation_rating",
    ),
    path(
        "evaluation/swtich",
        performance_views.switch_performance_evalution,
        name="switch_performance_evalution",
    ),
    path(
        "peer-evaluation/<str:evaluation_id>",
        performance_views.performance_peer_evaluation,
        name="selected_performance_peer_evaluation",
    ),
    path(
        "peer-evaluation",
        performance_views.performance_peer_evaluation,
        name="performance_peer_evaluation",
    ),
    path(
        "evaluation",
        performance_views.performance_evaluation,
        name="performance_evaluation",
    ),
    path(
        "section-switch",
        performance_views.switch_performance_management_section,
        name="switch_performance_management_section",
    ),
    path(
        "",
        performance_views.performance_management,
        name="performance_management",
    ),
]
