# Generated by Django 5.0.5 on 2024-07-29 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Questionnaire Content"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is Questionnaire Active"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="UserEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_date",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Evaluation Content Data"
                    ),
                ),
                (
                    "positive_feedback",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Positive Feedback To Evaluatee",
                    ),
                ),
                (
                    "improvement_suggestion",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Improvement Suggestion To Evaluatee",
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Evaluation Date"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "evaluatee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="evaluatee_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="evaluator_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="performance.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Evaluations",
            },
        ),
    ]
