# Generated by Django 5.0.5 on 2024-07-29 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userevaluation",
            name="content_date",
        ),
        migrations.RemoveField(
            model_name="userevaluation",
            name="date_submitted",
        ),
        migrations.RemoveField(
            model_name="userevaluation",
            name="evaluator",
        ),
        migrations.RemoveField(
            model_name="userevaluation",
            name="improvement_suggestion",
        ),
        migrations.RemoveField(
            model_name="userevaluation",
            name="positive_feedback",
        ),
        migrations.RemoveField(
            model_name="userevaluation",
            name="questionnaire",
        ),
        migrations.AddField(
            model_name="userevaluation",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Is User Evaluation Active"
            ),
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "positive_feedback",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Positive Feedback To Evaluatee",
                    ),
                ),
                (
                    "improvement_suggestion",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Improvement Suggestion To Evaluatee",
                    ),
                ),
                (
                    "content_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Evaluation Content Data"
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Evaluation Date"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="evaluator_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="performance.questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluations",
            },
        ),
        migrations.AddField(
            model_name="userevaluation",
            name="evaluators",
            field=models.ManyToManyField(
                related_name="user_evaluations", to="performance.evaluation"
            ),
        ),
    ]
