# Generated by Django 5.0.5 on 2024-07-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_remove_userevaluation_content_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userevaluation",
            old_name="is_active",
            new_name="is_finalized",
        ),
    ]
