# Generated by Django 5.0.5 on 2024-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_rename_is_active_userevaluation_is_finalized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevaluation",
            name="is_finalized",
            field=models.BooleanField(
                default=False, verbose_name="Is User Evaluation Finalized"
            ),
        ),
    ]
