# Generated by Django 5.0.5 on 2024-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0004_alter_userevaluation_is_finalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevaluation",
            name="quarter",
            field=models.CharField(
                blank=True,
                choices=[("FQ", "First Quarter"), ("SQ", "Second Quarter")],
                default=None,
                max_length=2,
                null=True,
                verbose_name="User Evaluaton Quarter",
            ),
        ),
    ]
