# Generated by Django 5.0.5 on 2024-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_userevaluation_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevaluation",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="User Evaluation Year"
            ),
        ),
    ]
