# Generated by Django 5.0.5 on 2024-07-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0006_userevaluation_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userevaluation",
            old_name="evaluators",
            new_name="evaluations",
        ),
    ]
