# Generated by Django 5.0.5 on 2024-07-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0007_rename_evaluators_userevaluation_evaluations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userevaluation",
            name="evaluations",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="user_evaluations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_evaluations",
                to="performance.userevaluation",
            ),
        ),
    ]
