# Generated by Django 5.0.5 on 2024-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0010_alter_evaluation_user_evaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Poll Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Poll Description"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, null=True, verbose_name="Poll Data"),
                ),
                (
                    "in_progress",
                    models.BooleanField(
                        default=True, verbose_name="Is Poll In Progress"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Polls",
            },
        ),
    ]
