# Generated by Django 5.0.5 on 2024-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0011_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="data",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="Poll Data"
            ),
        ),
    ]
