# Generated by Django 5.0.5 on 2024-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0012_alter_poll_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="multiple_selection",
            field=models.BooleanField(
                default=False, verbose_name="Allow Multiple Poll Selection"
            ),
        ),
    ]
