# Generated by Django 5.0.5 on 2024-08-15 04:17

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0013_poll_multiple_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", prose.fields.DocumentContentField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Post Title"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Post Active"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="performance.postcontent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
            },
        ),
    ]
