# Generated by Django 5.0.5 on 2024-08-15 07:21

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0014_postcontent_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
    ]
