# Generated by Django 5.0.5 on 2024-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0015_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Post Description"
            ),
        ),
    ]
