# Generated by Django 5.0.5 on 2024-08-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0016_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="performance.postcontent",
            ),
        ),
    ]
