# Generated by Django 5.0.5 on 2024-08-20 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import performance.utils


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0017_alter_post_body"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcontent",
            options={"verbose_name_plural": "Post Contents"},
        ),
        migrations.CreateModel(
            name="SharedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=performance.utils.get_shared_documents_directory_path,
                        verbose_name="Document",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shared_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_to_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shared Documents",
            },
        ),
    ]
