# Generated by Django 5.0.5 on 2024-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0018_alter_postcontent_options_shareddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareddocument",
            name="document_name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Document Name"
            ),
        ),
    ]
