# Generated by Django 5.0.5 on 2024-08-21 06:35

from django.db import migrations, models

import performance.utils


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0019_shareddocument_document_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareddocument",
            name="document_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=performance.utils.get_shared_documents_directory_path,
                verbose_name="Document PDF",
            ),
        ),
    ]
