# Generated by Django 5.0.5 on 2024-08-23 12:49

import django.db.models.deletion
import performance.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0020_shareddocument_document_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Resource Name",
                    ),
                ),
                (
                    "resource",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=performance.utils.get_shared_resources_directory_path,
                        verbose_name="Resource",
                    ),
                ),
                (
                    "resource_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=performance.utils.get_shared_resources_directory_path,
                        verbose_name="Resource as PDF",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shared_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_to_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shared Resources",
            },
        ),
        migrations.DeleteModel(
            name="SharedDocument",
        ),
    ]
