# Generated by Django 5.0.5 on 2024-08-29 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0021_sharedresource_delete_shareddocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedresource",
            name="confidential_access_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="confidential_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharedresource",
            name="is_confidential",
            field=models.BooleanField(
                default=False, verbose_name="Is Resource Confidential"
            ),
        ),
    ]
