# Generated by Django 5.0.5 on 2024-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Basic Salary Amount",
                    ),
                ),
                (
                    "history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Basic Salary History",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Basic Salary",
            },
        ),
    ]
