# Generated by Django 5.0.5 on 2024-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                (
                    "salary_grade",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Rank Salary Grade"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ranks",
            },
        ),
    ]
