# Generated by Django 5.0.5 on 2024-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Rank Active"),
        ),
    ]
