# Generated by Django 5.0.5 on 2024-09-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_user_role_userdetails_role"),
        ("payroll", "0003_rank_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ranks",
                to="core.department",
            ),
        ),
    ]
