# Generated by Django 5.0.5 on 2024-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_rank_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Rank Code"),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Rank Name"),
        ),
    ]
