# Generated by Django 5.0.5 on 2024-09-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_user_role_userdetails_role"),
        ("payroll", "0005_alter_rank_code_alter_rank_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Job Title")),
                ("code", models.CharField(max_length=10, verbose_name="Job Code")),
                (
                    "salary_grade",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Job Salary Grade"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Job Active"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="jobs",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.DeleteModel(
            name="Rank",
        ),
    ]
