# Generated by Django 5.0.5 on 2024-09-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_user_role_userdetails_role"),
        ("payroll", "0006_job_delete_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="department",
        ),
        migrations.AddField(
            model_name="job",
            name="department",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="core.department"
            ),
        ),
    ]
