# Generated by Django 5.0.5 on 2024-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_remove_job_department_job_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinumumWage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Minimum Wage Amount",
                    ),
                ),
                (
                    "history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Minimum Wage History",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Minimum Wage",
            },
        ),
        migrations.DeleteModel(
            name="BasicSalary",
        ),
    ]
