# Generated by Django 5.0.5 on 2024-09-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_minumumwage_delete_basicsalary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MinumumWage",
            new_name="MinimumWage",
        ),
    ]
