# Generated by Django 5.0.5 on 2024-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_userrank"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="userrank",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userrank",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
