# Generated by Django 5.0.5 on 2024-09-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_job_created_job_updated_userrank_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRank",
        ),
    ]
