# Generated by Django 5.0.5 on 2024-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_compensation_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="mandatory",
            field=models.BooleanField(
                default=False, verbose_name="Is Compensation Mandatory"
            ),
        ),
        migrations.AddField(
            model_name="deduction",
            name="mandatory",
            field=models.BooleanField(
                default=False, verbose_name="Is Deduction Mandatory"
            ),
        ),
    ]
