# Generated by Django 5.0.5 on 2024-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0014_compensation_mandatory_deduction_mandatory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Compensation",
        ),
        migrations.DeleteModel(
            name="Deduction",
        ),
    ]
