# Generated by Django 5.0.5 on 2024-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0015_delete_compensation_delete_deduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeductionConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Deduction Configuration",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Deduction Configuration",
                "verbose_name_plural": "Deduction Configurations",
            },
        ),
    ]
