# Generated by Django 5.0.5 on 2024-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_deductionconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="deductionconfiguration",
            name="history",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                verbose_name="Deduction Configuration History",
            ),
        ),
    ]
