# Generated by Django 5.0.5 on 2024-09-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0018_mp2"),
    ]

    operations = [
        migrations.AddField(
            model_name="mp2",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Contribution Amount",
            ),
        ),
    ]
