# Generated by Django 5.0.5 on 2024-09-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0020_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("DR", "Draft"), ("FI", "Finalized")],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Payslip Status",
            ),
        ),
    ]
