# Generated by Django 5.0.5 on 2024-09-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_payslip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Payslip Status"
            ),
        ),
    ]
