# Generated by Django 5.0.5 on 2024-09-16 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_alter_payslip_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Allowance"),
                            ("HO", "Honorarium"),
                            ("GG", "Government Grant"),
                            ("13", "13th Month"),
                            ("OT", "Others"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                        verbose_name="Compensation Type",
                    ),
                ),
                (
                    "specific_type",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Specific Type",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Compensation Month"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Compensation Month"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Compensations",
            },
        ),
    ]
