# Generated by Django 5.0.5 on 2024-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0023_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Compensation Amount",
            ),
        ),
    ]
