# Generated by Django 5.0.5 on 2024-09-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0024_compensation_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="compensations",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="deductions",
        ),
    ]
