# Generated by Django 5.0.5 on 2024-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0025_remove_payslip_compensations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="status",
        ),
        migrations.AddField(
            model_name="payslip",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[("1ST", "1st Period"), ("2ND", "2nd Period")],
                default=None,
                max_length=3,
                null=True,
                verbose_name="Salary Period",
            ),
        ),
    ]
