# Generated by Django 5.0.5 on 2024-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0026_remove_payslip_status_payslip_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="finalized",
            field=models.BooleanField(
                default=False, verbose_name="Is Payslip Finalized"
            ),
        ),
    ]
