# Generated by Django 5.0.5 on 2024-09-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0027_payslip_finalized"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DeductionConfiguration",
            new_name="MandatoryDeductionConfiguration",
        ),
        migrations.AlterModelOptions(
            name="mandatorydeductionconfiguration",
            options={
                "verbose_name": "Mandatory Deduction Configuration",
                "verbose_name_plural": "Mandatory Deduction Configurations",
            },
        ),
    ]
