# Generated by Django 5.0.5 on 2024-09-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0028_rename_deductionconfiguration_mandatorydeductionconfiguration_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableDeductionConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Deduction Name"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Deduction Amount",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payslip",
                        to="payroll.payslip",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Variable Deduction Configurations",
            },
        ),
    ]
