# Generated by Django 5.0.5 on 2024-09-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0029_variabledeductionconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variabledeductionconfiguration",
            name="payslip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="variable_deductions",
                to="payroll.payslip",
            ),
        ),
    ]
