# Generated by Django 5.0.5 on 2024-09-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0030_alter_variabledeductionconfiguration_payslip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="finalized",
        ),
        migrations.AddField(
            model_name="payslip",
            name="release_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Payslip Release Date"
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="released",
            field=models.BooleanField(
                default=False, verbose_name="Is Payslip Released"
            ),
        ),
    ]
