# Generated by Django 5.0.5 on 2024-09-20 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0031_remove_payslip_finalized_payslip_release_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedCompensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Compensation Amount",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Compensation Month"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Compensation Month"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Compensations",
            },
        ),
        migrations.DeleteModel(
            name="Compensation",
        ),
    ]
