# Generated by Django 5.0.5 on 2024-09-20 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0032_fixedcompensation_delete_compensation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixedcompensation",
            options={"verbose_name_plural": "Fixed Compensations"},
        ),
        migrations.AlterField(
            model_name="fixedcompensation",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Fixed Compensation Amount",
            ),
        ),
        migrations.AlterField(
            model_name="fixedcompensation",
            name="month",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Fixed Compensation Month"
            ),
        ),
        migrations.AlterField(
            model_name="fixedcompensation",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Fixed Compensation Name",
            ),
        ),
        migrations.AlterField(
            model_name="fixedcompensation",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="fixed_compensations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fixedcompensation",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Fixed Compensation Month"
            ),
        ),
    ]
