# Generated by Django 5.0.5 on 2024-09-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0034_variablecompensation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VariableDeductionConfiguration",
            new_name="VariableDeduction",
        ),
        migrations.AlterModelOptions(
            name="variablededuction",
            options={"verbose_name_plural": "Variable Deductions"},
        ),
    ]
