# Generated by Django 5.0.5 on 2024-09-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0035_rename_variabledeductionconfiguration_variablededuction_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirteenthMonthPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="13th Month Pay Amount",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="13th Month Pay Month"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="13th Month Pay Year"
                    ),
                ),
                (
                    "released",
                    models.BooleanField(
                        default=False, verbose_name="Is 13th Month Pay Released"
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="13th Month Pay Release Date",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Thirteenth Month Pays",
            },
        ),
    ]
