# Generated by Django 5.0.5 on 2024-10-01 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0036_thirteenthmonthpay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirteenthmonthpay",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="thirteenth_month_pays",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
