# Generated by Django 5.0.5 on 2024-10-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0037_alter_thirteenthmonthpay_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirteenthMonthPayVariableDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Deduction Name"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Deduction Amount",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "thirteenth_month_pay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="variable_deductions",
                        to="payroll.thirteenthmonthpay",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Thirteenth Month Pay Variable Deductions",
            },
        ),
    ]
