# Generated by Django 5.0.5 on 2024-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id_from_device",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Attendance UID From Device"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Attendance Timestamp"
                    ),
                ),
                (
                    "punch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Time In"),
                            ("OUT", "Time Out"),
                            ("OT_IN", "Overtime In"),
                            ("OT_OUT", "Overtime Out"),
                        ],
                        default=None,
                        max_length=6,
                        null=True,
                        verbose_name="Attendance Punch",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
