# Generated by Django 5.0.5 on 2024-07-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_user"),
        ("core", "0016_biometricdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.biometricdetail",
            ),
        ),
    ]
