# Generated by Django 5.0.5 on 2024-07-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Shift Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Shift End Time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shifts",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name_plural": "Attendances"},
        ),
        migrations.CreateModel(
            name="DailyAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "attendace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="attendance.attendance",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Attendance Records",
            },
        ),
    ]
