# Generated by Django 5.0.5 on 2024-07-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_shift_alter_attendance_options_dailyattendancerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shift Description"
            ),
        ),
        migrations.CreateModel(
            name="DailyShiftSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="daily_shift_schedules",
                        to="attendance.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Shift Schedules",
            },
        ),
        migrations.CreateModel(
            name="DailyShiftRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Daily Shift Record Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("PND", "Pending"), ("APV", "Approved")],
                        default=None,
                        max_length=3,
                        null=True,
                        verbose_name="Daily Shift Record Status",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "shifts",
                    models.ManyToManyField(
                        related_name="daily_shift_records",
                        to="attendance.dailyshiftschedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Shift Records",
            },
        ),
    ]
