# Generated by Django 5.0.5 on 2024-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_shift_description_dailyshiftschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Shift Is Active"),
        ),
    ]
