# Generated by Django 5.0.5 on 2024-07-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_shift_is_active"),
        ("core", "0023_alter_userdetails_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyshiftrecords",
            name="status",
        ),
        migrations.AddField(
            model_name="dailyshiftrecords",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="daily_shift_records",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="dailyshiftrecords",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Daily Shift Record Is Approved"
            ),
        ),
    ]
