# Generated by Django 5.0.5 on 2024-07-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_remove_dailyshiftrecords_status_and_more"),
        ("core", "0023_alter_userdetails_education"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyShiftRecords",
            new_name="DailyShiftRecord",
        ),
    ]
