# Generated by Django 5.0.5 on 2024-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_rename_dailyshiftrecords_dailyshiftrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyshiftrecord",
            name="shifts",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_shift_records",
                to="attendance.dailyshiftschedule",
            ),
        ),
    ]
