# Generated by Django 5.0.5 on 2024-07-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_dailyshiftrecord_shifts"),
        ("core", "0023_alter_userdetails_education"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyattendancerecord",
            name="attendace",
        ),
        migrations.RemoveField(
            model_name="dailyattendancerecord",
            name="shift",
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id_from_device",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Attendance Record User ID From Device",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Attendance Timestamp"
                    ),
                ),
                (
                    "punch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Time In"),
                            ("OUT", "Time Out"),
                            ("OT_IN", "Overtime In"),
                            ("OT_OUT", "Overtime Out"),
                        ],
                        default=None,
                        max_length=6,
                        null=True,
                        verbose_name="Attendance Record Punch",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.biometricdetail",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="DailyAttendanceRecord",
        ),
    ]
