# Generated by Django 5.0.5 on 2024-07-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_remove_dailyattendancerecord_attendace_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendancerecord",
            old_name="user",
            new_name="user_biometric_detail",
        ),
    ]
