# Generated by Django 5.0.5 on 2024-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_rename_user_attendancerecord_user_biometric_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Holiday Name"
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Holiday Day"
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Holiday Month"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Holiday Year"
                    ),
                ),
                (
                    "is_common",
                    models.BooleanField(
                        default=False, verbose_name="Is Holiday Common"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Holidays",
            },
        ),
    ]
