# Generated by Django 5.0.5 on 2024-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Holiday Name"
            ),
        ),
    ]
