# Generated by Django 5.0.5 on 2024-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_holiday_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="is_common",
        ),
        migrations.AddField(
            model_name="holiday",
            name="is_regular",
            field=models.BooleanField(default=False, verbose_name="Is Holiday Regular"),
        ),
    ]
