# Generated by Django 5.0.5 on 2024-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_overtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overtime",
            name="approved",
        ),
        migrations.AddField(
            model_name="overtime",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PEND", "Pending"), ("APP", "Approved"), ("REK", "Rejected")],
                default="PEND",
                max_length=4,
                null=True,
                verbose_name="Overtime Request Status",
            ),
        ),
    ]
