# Generated by Django 5.0.5 on 2024-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0016_remove_overtime_approved_overtime_status"),
        ("core", "0033_alter_notification_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="shifts", to="core.department"
            ),
        ),
    ]
