# Generated by Django 5.0.5 on 2024-10-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0017_shift_departments"),
        ("core", "0034_userdetails_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="user_biometric_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attendance_records",
                to="core.biometricdetail",
            ),
        ),
    ]
