# Generated by Django 5.0.5 on 2024-10-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0018_alter_attendancerecord_user_biometric_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyshiftschedule",
            name="clock_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="clock_in",
                to="attendance.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="dailyshiftschedule",
            name="clock_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="clock_out",
                to="attendance.attendancerecord",
            ),
        ),
    ]
