# Generated by Django 5.0.5 on 2024-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0019_dailyshiftschedule_clock_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyshiftschedule",
            name="clock_in",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Daily Shift Clock In"
            ),
        ),
        migrations.AlterField(
            model_name="dailyshiftschedule",
            name="clock_out",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Daily Shift Clock Out"
            ),
        ),
    ]
