# Generated by Django 5.0.5 on 2024-10-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0021_alter_dailyshiftschedule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="next_day_clock_out",
            field=models.BooleanField(
                default=False, verbose_name="Shift Is Next Day Clock Out"
            ),
        ),
    ]
