# Generated by Django 5.0.5 on 2024-10-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0022_shift_next_day_clock_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="next_day_clock_out",
        ),
        migrations.AddField(
            model_name="shift",
            name="multi_day",
            field=models.BooleanField(default=False, verbose_name="Shift Is Multi Day"),
        ),
    ]
