# Generated by Django 5.0.5 on 2024-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0023_remove_shift_next_day_clock_out_shift_multi_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyshiftschedule",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Daily Shift Schedule Date"
            ),
        ),
    ]
