# Generated by Django 5.0.5 on 2024-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0024_dailyshiftschedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="end_time_2",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Shift Second End Time"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="start_time_2",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Shift Second Start Time"
            ),
        ),
    ]
