# Generated by Django 5.0.5 on 2024-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0025_shift_end_time_2_shift_start_time_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyshiftschedule",
            name="clock_in",
        ),
        migrations.RemoveField(
            model_name="dailyshiftschedule",
            name="clock_out",
        ),
        migrations.AddField(
            model_name="dailyshiftschedule",
            name="attendance_records",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_shift_schedules",
                to="attendance.attendancerecord",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="punch",
            field=models.CharField(
                blank=True,
                choices=[("IN", "Time In"), ("OUT", "Time Out")],
                default=None,
                max_length=6,
                null=True,
                verbose_name="Attendance Record Punch",
            ),
        ),
    ]
