# Generated by Django 5.0.5 on 2024-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0026_remove_dailyshiftschedule_clock_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="departments",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="multi_day",
        ),
        migrations.AddField(
            model_name="shift",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
