# Generated by Django 5.0.5 on 2024-11-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0027_remove_shift_departments_remove_shift_multi_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyshiftschedule",
            name="attendance_records",
        ),
    ]
