# Generated by Django 5.0.5 on 2024-11-25 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0028_remove_dailyshiftschedule_attendance_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSwap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Is Shift Swap Approved"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shift_swaps_as_approver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="current_shift_swap_request",
                        to="attendance.dailyshiftschedule",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shift_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shift_swap_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requested_shift_swap_request",
                        to="attendance.dailyshiftschedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shift Swaps",
            },
        ),
    ]
