# Generated by Django 5.0.5 on 2024-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_shiftswap"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftswap",
            name="is_rejected",
            field=models.BooleanField(
                default=False, verbose_name="Is Shift Swap Rejected"
            ),
        ),
    ]
