# Generated by Django 5.1.7 on 2025-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0030_shiftswap_is_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftswap",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="Info"),
        ),
    ]
