# Generated by Django 5.1.7 on 2025-06-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_shiftswap_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtime",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="Info"),
        ),
    ]
