from django.urls import path

app_name = "payroll"

from payroll import views as payroll_views

urlpatterns = [
    path(
        "payroll-management/user-payslip/<str:payslip_id>/access",
        payroll_views.access_user_payslip,
        name="access_user_payslip",
    ),
    path(
        "payroll-management/user-payslip/view",
        payroll_views.view_user_payslip,
        name="view_user_payslip",
    ),
    path(
        "payroll-management",
        payroll_views.payroll_management,
        name="payroll_management",
    ),
    path(
        "payslip-management/update-payslip-data",
        payroll_views.update_payslip_data,
        name="update_payslip_data",
    ),
    path(
        "payslip-management/access/remove-other-payslip-deduction",
        payroll_views.remove_other_payslip_deduction,
        name="remove_other_payslip_deduction",
    ),
    path(
        "payslip-management/access/add-other-payslip-deduction",
        payroll_views.add_other_payslip_deduction,
        name="add_other_payslip_deduction",
    ),
    path(
        "payslip-management/access",
        payroll_views.access_payslip,
        name="access_payslip",
    ),
    path(
        "payslip-management",
        payroll_views.payslip_management,
        name="payslip_management",
    ),
    path(
        "salary-and-rank-management/compensations-settings/modify-specific-compensation-users",
        payroll_views.modify_specific_compensation_users,
        name="modify_specific_compensation_users",
    ),
    path(
        "salary-and-rank-management/compensations-settings/toggle-user-view",
        payroll_views.toggle_specific_compensation_users_view,
        name="toggle_specific_compensation_users_view",
    ),
    path(
        "salary-and-rank-management/compensations-settings/remove",
        payroll_views.remove_specific_compensation,
        name="remove_specific_compensation",
    ),
    path(
        "salary-and-rank-management/compensations-settings/modify",
        payroll_views.modify_specific_compensation,
        name="modify_specific_compensation",
    ),
    path(
        "salary-and-rank-management/compensations-settings/add",
        payroll_views.add_specific_compensation,
        name="add_specific_compensation",
    ),
    path(
        "salary-and-rank-management/compensations-settings",
        payroll_views.compensations_settings,
        name="compensations_settings",
    ),
    path(
        "salary-and-rank-management/mp2-amount-settings",
        payroll_views.mp2_amount_settings,
        name="mp2_amount_settings",
    ),
    path(
        "salary-and-rank-management/mp2-settings/toggle-status",
        payroll_views.toggle_user_mp2_status,
        name="toggle_user_mp2_status",
    ),
    path(
        "salary-and-rank-management/mp2-settings",
        payroll_views.mp2_settings,
        name="mp2_settings",
    ),
    path(
        "salary-and-rank-management/deductions-settings",
        payroll_views.deductions_settings,
        name="deductions_settings",
    ),
    path(
        "salary-and-rank-management/minimum-wage-settings",
        payroll_views.minimum_wage_settings,
        name="minimum_wage_settings",
    ),
    path(
        "salary-and-rank-management/delete-job",
        payroll_views.delete_job,
        name="delete_job",
    ),
    path(
        "salary-and-rank-management/modify-job",
        payroll_views.modify_job,
        name="modify_job",
    ),
    path(
        "salary-and-rank-management/view-job",
        payroll_views.view_job,
        name="view_job",
    ),
    path(
        "salary-and-rank-management/update-job-list",
        payroll_views.update_job_list,
        name="update_job_list",
    ),
    path(
        "salary-and-rank-management/add-job",
        payroll_views.add_job,
        name="add_job",
    ),
    path(
        "salary-and-rank-management/close-modals",
        payroll_views.payroll_module_close_modals,
        name="payroll_module_close_modals",
    ),
    path(
        "salary-and-rank-management",
        payroll_views.salary_and_rank_management,
        name="salary_and_rank_management",
    ),
]
